language: node_js

sudo: false

dist: trusty

node_js:
  - '10'

addons:
  sonarcloud:
    organization: "myerffoeg"
    token:
      secure: "Bn5YBHVoGQ3ISKtrc+1EMTN9tNmSLHpLhLMXVErFclanDstCPLk1BRzaZ23MIw9T308hIZGsskjN7G1Ca7kTrh7ju7Cn6UqbnlOZO+XfQLK0DTULtgEnvCakbaT4IS7kyVUeOfPsj5QNi7cm5OpYtEKKrshuWLgYP/6ABMRAuZRU30jneSEDZyAYylGhNc6MRt0DfRBfeWJ1/sngIxvOryp1GIeov644R6PW1xMkRJSmxOXvlH2axWd+v1xJUaH5vuRWHx5w9TpH4yg5rY4UB9Ra5Gyu4+N9DXx2ozysGB3gn76vThHGHdQn4YLWIL/jcuqBjNvEs696GSrNkqK+55CYt4FepJaLZEPxf/z8eCIOgTU95UflXrjT66y4ZPhgjlgmr01SvhrWoSrtw0RGeYkDXiBPqkE25TxwD5Bvr7rePDmCMAYu79yKnh3LeOOTZ6zhdh08TSRBRpi0n81hfRiPMcUNYn2mq6RL3GjHXCoRvkzMZ5vgEb7Nla9A/j/D7NoiF75T+aa4vMuHyuuyv8ujDisZ7Jx+hHQEGIMJo5vwGAIXjk9qcqAnI8p0YUxKU43BMpbUFhMcJLsRWl9Y/SyXsnRjqYL+wYYRqEL3dhcX/K+4vVDxM5Kj6U+r23hHXdWbe4RebBfgouTg8YgBoSbEQShgmD7U5BleCl5VAaQ="

script:
  - sonar-scanner

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: MasterOfTheGrid.user.js
  skip_cleanup: true
  on:
    tags: true

git:
  depth: 1